# Generated by Django 4.0.3 on 2022-03-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50)),
                ('types', models.CharField(max_length=50)),
                ('poid', models.FloatField()),
                ('chauffeur', models.CharField(max_length=50)),
                ('vitesse', models.IntegerField()),
                ('freinage', models.CharField(max_length=50)),
                ('consommation', models.CharField(max_length=50)),
            ],
        ),
    ]
