# Generated by Django 4.0.3 on 2022-03-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0003_livre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livre',
        ),
    ]
