# Generated by Django 4.0.3 on 2022-03-18 10:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0005_utilisateurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='chauffeurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('Birthday', models.DateField()),
                ('téléphone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('adresse', models.CharField(max_length=50)),
            ],
        ),
    ]
