# Generated by Django 4.0.3 on 2022-03-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0006_chauffeurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeurs',
            name='permis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chauffeurs',
            name='salaire',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
