# Generated by Django 4.0.3 on 2022-03-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0007_chauffeurs_permis_chauffeurs_salaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeurs',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
