# Generated by Django 4.0.3 on 2022-03-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0008_chauffeurs_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chauffeurs',
            old_name='téléphone',
            new_name='phone',
        ),
    ]
