# Generated by Django 4.0.3 on 2022-03-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0009_rename_téléphone_chauffeurs_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeurs',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
