# Generated by Django 4.0.3 on 2022-03-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0010_alter_chauffeurs_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateurs',
            old_name='téléphone',
            new_name='phone',
        ),
    ]
