# Generated by Django 4.0.3 on 2022-03-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0011_rename_téléphone_utilisateurs_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='usines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('age', models.DateField()),
                ('typeEgreneuse', models.CharField(max_length=50)),
                ('nbreEgreneuse', models.IntegerField()),
                ('capacite', models.FloatField()),
                ('personnelPermanent', models.IntegerField()),
                ('personnelSaisonnier', models.IntegerField()),
                ('personnelOccasionnel', models.IntegerField()),
            ],
        ),
    ]
