# Generated by Django 4.0.3 on 2022-03-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0012_usines'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
