# Generated by Django 4.0.3 on 2022-03-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0013_utilisateurs_is_active_utilisateurs_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borderauxdelivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerobordereau', models.IntegerField()),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=50)),
                ('modalitepaiement', models.CharField(max_length=50)),
                ('modalitelivraison', models.CharField(max_length=50)),
                ('datePaie', models.DateField()),
                ('delailivraison', models.DateField()),
                ('observation', models.CharField(max_length=50)),
                ('tauxremise', models.FloatField()),
            ],
        ),
    ]
