# Generated by Django 4.0.3 on 2022-03-26 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0014_borderauxdelivraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=50)),
                ('codeproduit', models.IntegerField()),
                ('datededepart', models.DateField()),
                ('adressededepart', models.CharField(max_length=50)),
                ('datearrive', models.DateField()),
                ('adressededestination', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=50)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.chauffeurs')),
            ],
        ),
    ]
