# Generated by Django 4.0.3 on 2022-03-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0015_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='chauffeur',
        ),
    ]
