# Generated by Django 4.0.3 on 2022-03-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0017_transactions_chauffeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
