# Generated by Django 4.0.3 on 2022-03-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0020_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
