# Generated by Django 4.0.3 on 2022-03-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0021_alter_utilisateurs_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
