# Generated by Django 4.0.3 on 2022-04-12 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0027_produits_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='codeproduit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.produits'),
        ),
    ]
