# Generated by Django 4.0.3 on 2022-04-12 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0029_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='facturedeproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numFacture', models.IntegerField()),
                ('PrixUnite', models.FloatField()),
                ('Qte', models.IntegerField()),
                ('total', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.clients')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.produits')),
            ],
        ),
    ]
