# Generated by Django 4.0.3 on 2022-04-13 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0032_rename_codeproduit_id_transactions_codeproduit'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('produit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.produits')),
            ],
        ),
    ]
