# Generated by Django 4.0.3 on 2022-04-13 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0033_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
