# Generated by Django 4.0.3 on 2022-04-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0034_delete_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='codeproduit',
            new_name='produit',
        ),
    ]
