# Generated by Django 4.0.3 on 2022-04-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0035_rename_codeproduit_transactions_produit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='produit',
            new_name='produits',
        ),
    ]
