# Generated by Django 4.0.3 on 2022-04-15 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0037_alter_transactions_produits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='produits',
        ),
        migrations.AddField(
            model_name='transactions',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_id', to='BackEnd.produits'),
        ),
    ]
