# Generated by Django 4.0.3 on 2022-04-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0040_remove_transactions_produits_transactions_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicules',
            name='chauffeur',
        ),
    ]
