# Generated by Django 4.0.3 on 2022-04-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0041_remove_vehicules_chauffeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicules',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
