# Generated by Django 4.0.3 on 2022-04-15 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0042_vehicules_marque'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.vehicules'),
        ),
    ]
