# Generated by Django 3.2.13 on 2022-04-29 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0046_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produits',
            name='emplacement',
        ),
        migrations.AddField(
            model_name='produits',
            name='mois',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('reference', models.CharField(max_length=50)),
                ('categorie', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('entre', models.FloatField()),
                ('sortie', models.FloatField()),
                ('mois', models.CharField(blank=True, max_length=50, null=True)),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.usines')),
            ],
        ),
    ]
