# Generated by Django 3.2.13 on 2022-05-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0052_alter_utilisateurs_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BackEnd.utilisateurs',),
        ),
    ]
