# Generated by Django 3.2.13 on 2022-05-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0056_responsabledeproduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='role',
            field=models.CharField(choices=[('gestionnaire logistique', 'Responsablelogistique'), ('administrateur', 'Administrateur'), ('cozoc', 'Cozoc'), ('responsable de production', 'Responsabledeproduction'), ('responsable financier', 'Responsablefinancier'), ('responsable de pont bascule', 'Responsabledepontbascule'), ('responsable CGI', 'Responsabledecgi')], default='administrateur', max_length=50),
        ),
    ]
