# Generated by Django 3.2.13 on 2022-05-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0059_responsabledepontbacule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cozoc',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('BackEnd.utilisateurs',),
        ),
    ]
