# Generated by Django 3.2.13 on 2022-05-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0061_ticketdepese'),
    ]

    operations = [
        migrations.CreateModel(
            name='besoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('code_AV', models.CharField(max_length=50, null=True)),
                ('nom_artc', models.CharField(max_length=50)),
                ('qte', models.FloatField()),
                ('unite', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('echeance', models.DateField()),
                ('prix', models.FloatField()),
            ],
        ),
    ]
