# Generated by Django 3.2.13 on 2022-05-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0062_besoins'),
    ]

    operations = [
        migrations.CreateModel(
            name='facturecoton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('qte', models.FloatField()),
                ('unite', models.CharField(max_length=10, null=True)),
                ('prixUnitaire', models.FloatField()),
                ('prixTotal', models.FloatField()),
                ('nom_AV', models.CharField(max_length=50)),
            ],
        ),
    ]
