# Generated by Django 3.2.13 on 2022-05-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0064_bordereauxlivraisonintrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='facturelivraisonintrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numfact', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('intrant', models.CharField(max_length=50)),
                ('qte', models.FloatField()),
                ('prixunitaire', models.FloatField()),
                ('prixtotal', models.FloatField()),
                ('modal_liv', models.CharField(max_length=50)),
                ('echeance', models.DateField()),
                ('observation', models.CharField(max_length=50)),
            ],
        ),
    ]
