# Generated by Django 3.2.13 on 2022-05-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0065_facturelivraisonintrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockcoton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencecoton', models.CharField(max_length=50)),
                ('entre', models.FloatField()),
                ('sortie', models.FloatField()),
                ('av', models.CharField(max_length=50)),
                ('mois', models.IntegerField()),
                ('usine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.usines')),
            ],
        ),
    ]
